config/routes.rb
ArtzibitDev::Application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    passwords: "users/passwords",
    mailers: "users/mailer"
  }

  get "page/home"

  resources :charges
  resources :test_users, only: [:create]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # match "/auth/:provider/callback" => "sessions#create"
  # match "/signout" => "sessions#destroy", :as => :signout
  # match "/signin" => "sessions#new", :as => :signin
  resources :users, only: [:show]
  resources :artwork_styles, only: [:index]
  resources :orders, only: [:show]
  resources :artworks, only: [:index, :show, :new, :create, :edit, :update,
    :destroy] do
    collection do
      get "crop/:id", action: "crop", as: "crop"
      get "reprocess/:id", action: "reprocess", as: "reprocess"
    end
  end
  resources :artwork_approval_dtls, only: [:show]

  # ==================================================== #
  # =============  API Routes - Version 1  ============= #
  # ==================================================== #
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      devise_scope :user do
        scope "/users" do
          resources :registrations, only: [:create, :update, :destroy]
          resources :sessions, only: [:create, :destroy]
          resources :passwords, only: [:create]
        end
      end
      resources :users, only: [:show]
      resources :size_options, only: [:index]
      resources :categories, only: [:index]
      resources :artworks, only: [:index, :show, :new, :create, :edit, :update,
        :destroy]
      resources :artists, only: [:index]
      resources :user_favorites, only: [:index, :create, :update]
      resources :artwork_styles, only: [:index]
      resources :sizes, only: [:index]
      resources :event_batches, only: [:index, :show]
      resources :user_checked_ins, only: [:create]
      resources :carts, only: [:index, :show, :create, :update]
      resources :users, only: [:update]
      resources :orders, only: [:index, :show]
      resources :user_shipping_details, only: [:index, :create, :destroy, :update]
      resources :filters, only: [:index]
      resources :user_bank_details, only: [:index, :create]
      resources :artwork_markers, only: [:create]
      resources :user_views, only: [:create]
      resources :user_launch_app_counters, only: [:create]
      resources :user_app_tracking_logs, only: [:create]
      resources :user_activation_codes, only: [:create]
    end
  end
  root :to => "page#home"
end

app/views/page/_home_banner.html.erb
<div class="row">
  <div class="col-md-5 col-md-offset-1 col-sm-5 col-sm-offset-1 col-xs-5
    col-xs-offset-1">
    <br/><br/>
    <%= image_tag "welcome.png", width: "100%", class: "welcome-image" %>
    <p> We help you sell, reproduce and market your work without you having to worry about the tedious
details. The minute you upload your work, we start working our magic. </p>
    <%= link_to "START UPLOADING", new_artwork_path, class:"btn btn-lg btn-default
      start-upload-button" %>
  </div>
  <div class="col-md-4 col-md-offset-1 col-sm-6 col-xs-6" id="start-upload-button">
    <%= image_tag "3_artworks.png", width: "100%", height: "100%", class: "artwork-sample" %>
  </div>
</div>

app/views/page/_login.html.erb
<div id="page-mask-signin" style="display:none;"%>
  <div class="sign_in_form col-md-4 col-md-offset-4 col-xs-4 col-xs-offset-4">
    <span class="close close-login"> <%= image_tag "close.png" %></span>
    <div id="new_user_form">
      <%= form_for(@user, as: :user, url: session_path(:user)) do |f| %>
<!--         <div class="row">
          <%# unless flash[:alert].blank? %>
            <%# flash.each do |key, value| %>
              <%#= content_tag :div, value, id: "#{key}" do %>
                <span class="<%#= key %>"> <%#= flash["#{key}"]%> </span>
                <hr>
              <% #end %>
            <%# end %>
          <% #end %>
        </div> -->
        <div class="row">
          <%= link_to "SIGN IN WITH FACEBOOK", new_session_path(@user),
            class: "btn btn-primary form-control like-button" %>
        </div>
        <div class="row">
          <div class="col-md-4">
            <hr>
          </div>
          <div class="col-md-4">
            <h4 style="color:gray;"> OR </h4>
          </div>
          <div class="col-md-4">
            <hr>
          </div>
        </div>
          <div class="row">
            <div class="form-group">
            <%= f.email_field :email, autofocus: true, class: "form-control like-button" %>
            </div>
            <div class="form-group">
              <%= f.password_field :password, autocomplete: "off", class: "form-control like-button" %>
              <%= link_to "Forgot your password?", "#", id: "forgot-password-link"%>
            </div>
          </div>
          <div class="row">
            <%= f.submit "SIGN IN", class: "btn btn-secondary log-in-submit form-control like-button" %>
          </div>
        <div class="row">
          <p> Not a member yet? <%= link_to " Sign up here.", new_registration_path(:user) %> </p>
        </div>
      <% end %>
    </div>
    <div id="forgot-password-form" style="display:none;">
      <%= form_for(@user, as: :user, url: password_path(:user), html: { method: :post }) do |f| %>
<!--           <div class="row">
            <%# unless flash[:alert].blank? %>
              <%# flash.each do |key, value| %>
                <%#= content_tag :div, value, id: "#{key}" do %>
                  <span class="<%#= key %>"> <%#= flash["#{key}"]%> </span>
                  <hr>
                <%# end %>
              <%# end %>
            <%# end %>
          </div> -->
          <div class="row">
            <p> <h5 class="forgot-header"> FORGOT YOUR PASSWORD?</h5> </p>
          </div>
          <div class="row">
            <p class="forgot-subheader"> No worries, enter your email below and we'll send password
              reset instructions to you.</p>
          </div>
          <div class="row">
            <div class="form-group">
              <%= f.email_field :email, autofocus: true, class: "form-control like-button",
                placeholder: "Email Address*"%>
            </div>
          </div>
          <div class="row">
            <%= f.submit "RESET PASSWORD", class: "btn btn-secondary log-in-submit form-control like-button" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  var sign_in_form = document.getElementById('sign_in_form');
  var mask = document.getElementById('page-mask-signin');
  var span = document.getElementsByClassName("close-login")[0];
  var forgot = document.getElementById("forgot-password-link");
  var forgot_form = document.getElementById("forgot-password-form");
  span.onclick = function() {
    if (sign_in_form) {
      sign_in_form.style.display = "none";
    }
    mask.style.display = "none";
    if (forgot_form) {
      forgot_form.style.display = "none";
    }
  }
  if (forgot) {
    forgot.onclick = function() {
      sign_form = document.getElementById("new_user_form");
      sign_form.style.display = "none";
      forgot_form.style.display = "inline";
    }
  }
</script>

app/views/page/home.html.erb
<%= stylesheet_link_tag "devise", :media => "all" %>
<div class="row">
  <div class="col-md-12 col-sm-12">
    <div class="jumbotron jumbotron-home" style="background: url(<%=image_path('microsite-bg-01.jpg')%>)">
      <%= render "home_banner" %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron-email">
      <div class="col-md-8 col-md-offset-2">
          <table border=0 width="100%">
          <tr> <td>
            <span class="email-textbox-label">
              GET FIRST DIBS. <br/>
              TRY OUT ARTZIBIT TODAY.
            </span> </td> <td>
            <%= form_for @test_user, onsubmit: "return check_test_user_field();",
              html: {autocomplete: "off"} do |f| %>
              <%= f.text_field :email, class: "email-textbox", placeholder: "Enter email here"%>
              <%= image_submit_tag image_path("arrow.jpg"), class: "email-button", onclick: "return check_test_user_field()" %>
            <% end %> </td> </tr>
          </table>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron-counter">
      <br/><br/>
      <div class="col-md-8 col-md-offset-2">
        <div class="row">
          <div class="col-md-3 col-sm-3 col-xs-6 counter-box">
            <center>
              <div class="row">
                <span class="counter">
                  <%= total_artists %>
                </span>
              </div>
              <div class="row artist-row">
                <span class="counter-label">
                  <p> TOTAL ARTISTS </p>
                </span>
              </div>
            </center>
          </div>
          <div class="col-md-3 col-sm-3 col-xs-6 counter-box">
            <center>
              <div class="row">
                <span class="counter">
                  <%= photographers %>
                </span>
              </div>
              <div class="row">
                <span class="counter-label">
                  <p> PHOTOGRAPHERS </p>
                </span>
              </div>
            </center>
          </div>
          <div class="col-md-3 col-sm-3 col-xs-6 counter-box">
            <center>
              <div class="row">
                <span class="counter">
                  <%= visual_artists %>
                </span>
              </div>
              <div class="row visual-row">
                <span class="counter-label">
                  <p> VISUAL ARTISTS </p>
                </span>
              </div>
            </center>
          </div>
          <div class="col-md-3 col-sm-3 col-xs-6 counter-box" style="border-right: white 1px solid;">
            <center>
              <div class="row">
                <span class="counter">
                  <%= total_artworks %>
                </span>
              </div>
              <div class="row">
                <span class="counter-label">
                  <p> TOTAL ARTWORKS </p>
                </span>
              </div>
            </center>
          </div>
        </div>
        <br/><br/>
      </div>
    </div>
  </div>
</div>
<%= render "shared/flash" %>